pipeline {
    agent { label 'windows' }
    environment {
        VERSION = getVersion()
        OCTOPUS_API_KEY = credentials('octopus-api-key')
    }
    stages {
        stage ('Build with Cake') {
            steps {
                script {
                    def status = powershell(returnStatus: true, script: "./build.ps1")
                    if (status != 0) {
                        // Use SUCCESS FAILURE or ABORTED
                        currentBuild.result = "FAILURE"
                        throw new Exception("Exit code from Cake Build: ${status}.")
                    }
                }
            }
        }
        stage ('Push Package to Octopus') {
            when { branch 'pushpay_master' }
            steps {
                script {
                    octopusPushPackage \
                        toolId: 'windows-octo', \
                        serverId: 'rktapps-octopus', \
                        spaceId: 'Spaces-1', \
                        overwriteMode: 'FailIfExists', \
                        packagePaths: "**/output/StackExchange.Opserver.${VERSION}.nupkg"
                }
            }
        }
        stage ('Push Package Information to Octopus') {
            when { branch 'pushpay_master' }
            steps {
                script {
                    octopusPushBuildInformation \
                        toolId: 'windows-octo', \
                        serverId: 'rktapps-octopus', \
                        spaceId: 'Spaces-1', \
                        commentParser: 'GitHub', \
                        overwriteMode: 'FailIfExists', \
                        packageId: 'StackExchange.Opserver', \
                        packageVersion: "${VERSION}", \
                        verboseLogging: false, \
                        gitUrl: "${GIT_URL}", \
                        gitBranch: "${GIT_BRANCH}", \
                        gitCommit: "${GIT_COMMIT}"
                }
            }
        }
        stage ('Trigger Octopus Release Creation') {
            when { branch 'pushpay_master' }
            steps {
                script {
                    def packages = [
                        [packageName: "Configure IIS site", packageReferenceName: "StackExchange.Opserver", packageVersion: "${env.VERSION}"]
                    ]

                    octopusCreateRelease \
                        toolId: 'windows-octo', \
                        serverId: 'rktapps-octopus', \
                        spaceId: 'Spaces-1', \
                        project: 'Opserver', \
                        releaseVersion: "${env.VERSION}", \
                        packageConfigs: packages, \
                        deployThisRelease: true, \
                        cancelOnTimeout: false, \
                        waitForDeployment: true, \
                        deploymentTimeout: '00:15:00', \
                        environment: 'test', \
                        jenkinsUrlLinkback: true, \
                        releaseNotes: true, \
                        releaseNotesSource: 'scm'
                }
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: "**/output/StackExchange.Opserver.${VERSION}.nupkg", fingerprint: true, allowEmptyArchive: true
        }
    }
}

def getVersion() {
    if(env.BRANCH_NAME == "pushpay_master") {
        return "1.1.0.${BUILD_NUMBER}"
    }

    return "1.1.1.${BUILD_NUMBER}"
}
